[package]
name = "chess"
version.workspace = true
edition = "2021"

[dependencies]
cozy-chess = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = "1.4"
