[package]
name = "chess"
version = "0.1.0"
edition = "2021"

[dependencies]
cozy-chess = { workspace = true }
thiserror = { workspace = true }
chess-common = { path = "../chess-common" }

[dev-dependencies]
proptest = "1.4"
