[package]
name = "chesstty"
version.workspace = true
edition = "2021"

[[bin]]
name = "chesstty"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
