[package]
name = "analysis"
version.workspace = true
edition = "2021"

[dependencies]
chess = { path = "../chess" }
cozy-chess = { workspace = true }
serde = { workspace = true }
smallvec = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
